### ISSUE TITLE
fyi: web ide button failed to start the lab

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/react-simple-state-lab#1]
requires local version through forked copy for the lab server to start.

**Comment by maxwellbenton** [comment]
Hi @ICanDoAllThingThroughChrist,

Thank you for letting us know. At the moment, the In-Browser IDE is actually only meant to be used in the earlier sections of our courses, mainly in Ruby. While it is enabled and may work with some JS labs, most React labs use `react-scripts` to run the server that lets us view React apps in-browser and live update them with code changes, which won't work on the in-browser IDE.

Because the in-broswer IDE will not work consistently for our JavaScript and more advanced materials, we advise online students to begin using a local environment after they complete the Sinatra project: https://help.learn.co/en/articles/492944-using-the-ide-versus-a-local-environment

Since this is not a problem specific to this lab, I am going to close this issue. We apologize for any frustration this lab may have caused you, but we appreciate you taking the time to provide feedback!

Thank you!
