### ISSUE TITLE
We haven't learned about click handlers

### ISSUE THREAD

**Issue by kjgenevieve** [learn-co-curriculum/react-simple-state-lab#3]
Click handlers need to be explained in the reading or a resource should be given (and its purpose explicitly stated).

**Comment by maxwellbenton** [comment]
Hi @kjgenevieve,

Thank you for providing this feedback. We are in the process of updating our React materials and are gathering known order issues together to address in an upcoming update. I've noted this issue [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3) in our general issue for this update and we will likely move this lab to a slightly later position so that events are introduced first.

Since we're now tracking this problem in a separate location, I am going to close this issue for now. We will follow up with you here once this issue is resolved and the lab is relocated.

Thank you for helping us improve our curriculum!
